package model

import (
	"fmt"
	"strings"
)

const separator = "┃"

type Station struct {
	// Changeuuid  string `json:"changeuuid"`  // A globally unique identifier for the change of the station information
	// Serveruuid  interface{} `json:"serveruuid"`
	// URLResolved     string      `json:"url_resolved"`
	// Favicon         string      `json:"favicon"`

	Stationuuid string `json:"stationuuid"` // A globally unique identifier for the station
	Name        string `json:"name"`        // 	The name of the station
	URL         string `json:"url"`         // The stream URL provided by the user
	// An automatically "resolved" stream URL. Things resolved are playlists (M3U/PLS/ASX...), HTTP redirects (Code 301/302).
	// This link is especially usefull if you use this API from a platform that is not able to do a resolve on its own (e.g. JavaScript in browser)
	// or you just don't want to invest the time in decoding playlists yourself.
	Homepage        string      `json:"homepage"`    // URL to the homepage of the stream, so you can direct the user to a page with more information about the stream.
	Tags            string      `json:"tags"`        // Tags of the stream with more information about it
	Country         string      `json:"country"`     //  	DEPRECATED: use countrycode instead, full name of the country. Currently it is autogenerated from the countrycode.
	Countrycode     string      `json:"countrycode"` // Official countrycodes as in ISO 3166-1 alpha-2
	State           string      `json:"state"`
	Language        string      `json:"language"` // string, multivalue, split by comma 	Languages that are spoken in this stream.
	Votes           int64       `json:"votes"`    // Number of votes for this station. This number is by server and only ever increases. It will never be reset to 0.
	Codec           string      `json:"codec"`
	Bitrate         int64       `json:"bitrate"`
	Lastcheckoktime string      `json:"lastcheckoktime"`
	Clickcount      int64       `json:"clickcount"`
	Clicktrend      int64       `json:"clicktrend"`
	GeoLat          interface{} `json:"geo_lat"`
	GeoLong         interface{} `json:"geo_long"`

	IsCustom bool `json:"-"`
}

func (s Station) Title() string { return s.Name }
func (s Station) Description() string {
	desc := s.Countrycode
	if strings.TrimSpace(s.State) != "" {
		desc += ", " + s.State
	}
	if strings.TrimSpace(s.Language) != "" {
		desc += ", " + s.Language
	}
	if strings.TrimSpace(desc) == "" {
		desc = "-"
	}
	bitrateS := "  - kbps"
	if s.Bitrate != 0 {
		bitrateS = fmt.Sprintf("%3d kbps", s.Bitrate)
	}
	desc = fmt.Sprintf("Votes: %6[2]d, Clicks: %5[6]d %[1]s %[3]s %[1]s %[4]s %[1]s %[5]s",
		separator, s.Votes, bitrateS, desc, s.Tags, s.Clickcount)
	desc = strings.TrimSpace(desc)
	desc = strings.Trim(desc, "|")
	desc = strings.TrimSpace(desc)
	return desc
}
func (s Station) FilterValue() string { return s.Name }
