version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      # - CC=gcc
    ldflags:
      - -s -w
      - "-X main.version={{ .Version }}"
    gcflags:
      - all=-trimpath

  - id: darwin
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - -s -w
      - "-X main.version={{ .Version }}"
    gcflags:
      - all=-trimpath

  - id: windows
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
      # - CC=gcc
    ldflags:
      - -s -w
      - "-X main.version={{ .Version }}"
    gcflags:
      - all=-trimpath

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
